<?php namespace LogDigest\Test;

class DigestTest extends AbstractTest
{
	public function run()
	{
		$email = $this->data['email'];
		$validator = $this->app->validator('Email');
		if (!$validator->isValid($email, $error))
		{
			$this->errorMessage(\XF::phrase('logdigest_invalid_email_address'));
			return false;
		}

		$generate = $this->getCheckbox('generate');

		if ($generate)
		{
			// create a test exception so we have log data to return
			\XF::logException(new \Exception("This is a test exception generated by the LogDigest addon"));
		}

		$logs = \XF::finder('XF:ErrorLog')->order('exception_date', 'DESC')->limit(10)->fetch();

		$params = [
			'type' => "[Test] Server error",
			'route' => 'logs/server-errors',
			'logs' => $logs,
		];

		$this->app->mailer()->newMail()
			->setTo($email)
			->setTemplate('logdigest_server_error', $params)
			->send();
	}
}
