<?php namespace Hampel\LogDigest\Test;

class ServerErrorLog extends AbstractTest
{
	protected function run()
	{
		$generate = $this->getCheckbox('generate');

		if ($generate)
		{
			// create a test exception so we have log data to return
			\XF::logException(new \Exception("This is a test exception generated by the LogDigest addon"));
		}

		return $this->send('Hampel\LogDigest:ServerErrorLog');
	}
}
